const cocktailFacts = [
  "The term 'cocktail' first appeared in print in the early 19th century.",
  "During the Prohibition era, speakeasies flourished.",
  "One theory suggests the word 'cocktail' originated from the practice of adding a rooster's tail feather to drinks.",
  "During World War II, many classic cocktails were created due to the rationing of certain spirits.",
  "The first cocktail shaker patent was issued in the 19th century.",
  "Tiki bars and tiki cocktails became popular in the mid-20th century.",
  "The first cocktail recipe book, 'The Bartender's Guide,' was published in 1862.",
  "The late 20th and early 21st centuries saw a cocktail renaissance.",
  "The Sazerac, one of the oldest known cocktails, is named after a brand of cognac.",
  "The first commercial ice machine revolutionized the way cocktails were served.",
  "The world's most expensive cocktail, The Winston, was priced at $12,970.",
  "Many cocktails have multiple origin stories, often disputed among bartenders and historians.",
  "The period from the late 19th century to the early 20th century is often referred to as the Golden Age of Cocktails.",
  "Cocktail straws were often made from natural ryegrass or bamboo before plastic straws became common.",
  "Absinthe was banned in many countries in the early 20th century due to concerns over its alleged hallucinogenic effects.",
  "Hollywood movies have popularized various cocktails, such as the White Russian in 'The Big Lebowski.'",
  "Ada Coleman, known as 'Coley,' was one of the first famous female bartenders.",
  "The concept of cocktail parties became popular in the 1920s.",
  "Bitters have experienced a revival in recent years, with many artisanal brands emerging.",
  "Many celebrities have cocktails named after them, such as the 'Marilyn Monroe' cocktail.",
  "The first frozen daiquiri machine was invented in 1938 in Havana, Cuba.",
  "The Museum of the American Cocktail, located in New Orleans, was founded in 2004.",
  "New cocktails created in recent decades, such as the Penicillin, have already achieved classic status.",
  "The term 'cocktail hour' originated in the early 20th century.",
  "Japanese bartending is known for its precision and unique techniques.",
  "Cocktail festivals, such as Tales of the Cocktail, celebrate cocktail culture.",
  "The quality of ice has become an important aspect of cocktail making in high-end bars.",
  "Many bars offer a 'Bartender's Choice' option for custom cocktails.",
  "Rye whiskey has seen a resurgence in popularity in recent years.",
  "The farm-to-table movement has extended to cocktails with bartenders using fresh, locally-sourced ingredients.",
  "Modern cocktail books have become bestsellers and essential references for bartenders.",
  "The Spirited Awards recognize excellence in the cocktail industry.",
  "Sustainability has become a focus in the cocktail industry with eco-friendly practices.",
  "Bartenders continue to innovate using new techniques and ingredients.",
  "The British Royal Navy issued a daily rum ration to sailors until 1970, known as 'grog.'",
  "Bartenders like Jerry Thomas, Harry Craddock, and Ada Coleman have left a lasting legacy.",
  "Modern speakeasies offer an intimate and often secretive cocktail experience.",
  "Classic cocktail tools, such as the jigger and the muddler, remain essential in bartending.",
  "Cocktail umbrellas, often used in tiki drinks, were first popularized in the 1930s and 1940s.",
  "The Golden Age of Cocktails saw the creation of many classic cocktails and the rise of professional bartending.",
  "Cocktail renaissance in the late 20th and early 21st centuries renewed interest in classic cocktails.",
  "Absinthe, known as 'the Green Fairy,' was re-legalized in the U.S. in 2007.",
  "The White Russian gained popularity in the 1990s thanks to the movie 'The Big Lebowski.'",
  "The Aviation cocktail's beautiful blue color comes from crème de violette.",
  "The longest permanent bar in the world is in Rock Island, Illinois, measuring 684 feet.",
  "The British Royal Navy created the Gin and Tonic to make quinine more palatable.",
  "During Prohibition, cocktails became very popular to mask the taste of poorly made spirits.",
  "Cocktails often have interesting names, such as the Moscow Mule named for its Russian vodka and the 'kick' of ginger beer.",
  "The Old Fashioned is considered one of the oldest cocktails, dating back to the early 19th century.",
  "The Margarita was invented in Mexico in the 1930s or 1940s, with several stories about its origin.",
  "The Cosmopolitan gained widespread popularity in the 1990s thanks to the TV show 'Sex and the City.'",
  "The Mojito became internationally popular thanks to Ernest Hemingway, who enjoyed the drink in Havana.",
  "The Piña Colada was created in Puerto Rico in the 1950s and became the country's national drink in 1978.",
  "The Whiskey Sour, made with whiskey, lemon juice, and sugar, dates back to the 1860s.",
  "The Bloody Mary, often considered a hangover cure, is made with vodka, tomato juice, and various spices.",
  "The Mai Tai was created in 1944 at Trader Vic's in Oakland, California.",
  "The Zombie cocktail, a potent tiki drink, was invented by Donn Beach in the 1930s.",
  "The Espresso Martini, a modern classic, was created by bartender Dick Bradsell in the 1980s in London.",
  "The Singapore Sling was created at Raffles Hotel in Singapore in the early 20th century.",
  "The French 75, made with gin, lemon juice, sugar, and champagne, was named after a powerful French field gun used during World War I.",
  "The Corpse Reviver family of cocktails were originally designed as hangover cures, with the Corpse Reviver #2 being the most famous.",
  "The Irish Coffee, made with hot coffee, Irish whiskey, sugar, and cream, was invented in the 1940s to warm up travelers arriving in Ireland.",
  "The Caipirinha, Brazil's national cocktail, is made with cachaça, sugar, and lime.",
  "The Brandy Alexander, a creamy and decadent cocktail, was popular in the early 20th century.",
  "The Cuba Libre, made with rum, cola, and lime, was created in Cuba in the early 20th century.",
  "The Dark 'n' Stormy, Bermuda's national drink, is made with dark rum and ginger beer.",
  "The Bee's Knees, a Prohibition-era cocktail, is made with gin, lemon juice, and honey.",
  "The Ramos Gin Fizz, a New Orleans classic, is known for its frothy texture, created by shaking gin, lemon and lime juice, simple syrup, egg white, cream, orange flower water, and soda water.",
  "The Pisco Sour, the national drink of Peru and Chile, is made with pisco, lime juice, simple syrup, egg white, and bitters.",
  "The Paloma, a popular Mexican cocktail, is made with tequila, grapefruit soda, and lime juice.",
  "The Hemingway Daiquiri, named after the famous author, is made with rum, lime juice, grapefruit juice, and maraschino liqueur.",
  "The Death in the Afternoon, another Hemingway-inspired cocktail, is made with absinthe and champagne.",
  "The Negroni was invented in Florence, Italy, in 1919 when Count Camillo Negroni asked for his Americano to be strengthened with gin instead of soda water.",
  "The Gin Rickey, a classic highball, is made with gin, lime juice, and soda water.",
  "The Martini has many variations, including the Dry Martini, Dirty Martini, and Gibson.",
  "The Aperol Spritz, an Italian aperitif cocktail, is made with Aperol, Prosecco, and a splash of soda water.",
  "The Bellini, a classic brunch cocktail, is made with Prosecco and peach puree.",
  "The Pimm's Cup, a refreshing British summer drink, is made with Pimm's No. 1, lemonade, and various fruits and herbs.",
  "The Corpse Reviver #2, a hangover cure, is made with gin, Cointreau, Lillet Blanc, lemon juice, and a dash of absinthe.",
  "The Red Snapper is a gin-based version of the Bloody Mary, created at the St. Regis Hotel in New York.",
  "The Planter's Punch, a classic rum punch, originated in Jamaica and is made with rum, lime juice, sugar, and various spices.",
  "The Alabama Slammer, a sweet and fruity cocktail, was popular in the 1970s and 1980s.",
  "The Harvey Wallbanger, a popular cocktail in the 1970s, is made with vodka, Galliano, and orange juice.",
  "The Golden Cadillac, a creamy cocktail, was created in the 1950s and is made with Galliano, crème de cacao, and cream.",
  "The Japanese Cocktail, a pre-Prohibition drink, is made with brandy, orgeat syrup, and bitters.",
  "The Godfather, a simple cocktail, is made with Scotch whisky and amaretto.",
  "The Bourbon Renewal, a modern cocktail, is made with bourbon, lemon juice, crème de cassis, and simple syrup.",
  "The Sea Breeze, a light and refreshing cocktail, is made with vodka, cranberry juice, and grapefruit juice.",
  "The Bay Breeze, a variation of the Sea Breeze, is made with vodka, cranberry juice, and pineapple juice.",
  "The Madras, another vodka cocktail, is made with vodka, cranberry juice, and orange juice.",
  "The Fuzzy Navel, a sweet and fruity cocktail from the 1980s, is made with peach schnapps and orange juice.",
  "The Singapore Sling is a complex cocktail made with gin, cherry brandy, Benedictine, Cointreau, grenadine, pineapple juice, lime juice, and bitters.",
  "The Long Island Iced Tea, a potent cocktail, is made with vodka, rum, gin, tequila, triple sec, lemon juice, simple syrup, and cola.",
  "Tommy's Margarita is a modern variation of the classic Margarita, made with agave nectar instead of triple sec.",
  "The Bramble, a refreshing cocktail, is made with gin, lemon juice, simple syrup, and blackberry liqueur.",
];

export default cocktailFacts;
