"""empty message

Revision ID: 38f30d48741f
Revises: a7a3a31f1668
Create Date: 2024-05-28 15:45:55.243148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f30d48741f'
down_revision = 'a7a3a31f1668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cocktails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('cocktails', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
